# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lintAllTheThings:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Fedora Core Config Transpiler
      run: |
        exit 1
        podman pull quay.io/coreos/fcct:release
        sudo bash -c "podman run --rm -v ./ignition/lb.yaml:/config.fcc:z quay.io/coreos/fcct:release --pretty --strict /config.fcc" 
    - name: Virt XML Validate
      run: |
        exit 1
        sudo DEBIAN_FRONTEND=noninteractive apt-get update
        sudo DEBIAN_FRONTEND=noninteractive apt-get install libvirt-clients libvirt-daemon
        sudo virt-xml-validate okd-net.xml network
        sudo virt-xml-validate ./libvirt-xml/lb-libvirt.xml domain
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Build the VMs
      run: |
        sudo bash -x ./fcct-create-ign.sh
        mkdir -p .ssh
        sudo chown runner:runner ssh.key
        cat ssh.key >> .ssh/id_rsa
        sudo DEBIAN_FRONTEND=noninteractive apt-get update
        sudo systemctl stop apparmor
        sudo apt remove --assume-yes --purge apparmor
        sudo DEBIAN_FRONTEND=noninteractive apt-get install libvirt-clients virtinst libvirt-daemon-system
        sudo systemctl start libvirtd
        sudo bash -x lib-virt-provision.sh
        until ssh -i ssh.key -o "StrictHostKeyChecking=no" core@10.20.15.2 echo "ssh key works!"
        do
          sleep 10
        done
        exit 1
        # apt-file
        # sudo DEBIAN_FRONTEND=noninteractive apt-file update
        # sudo apt-file find /usr/bin/qemu-system-x86_64
        
